### ISSUE TITLE
deduplicate functionality in genomcmcgan_*.py files

### ISSUE THREAD

**Issue by grahamgower** [RacimoLab/genomcmcgan#1]
The three files `genomcmcgan_joint.py`, `genomcmcgan_uniparam_gauss.py`, and `genomcmcgan_uniparam_simple.py` have mostly the same content, with some modifications. We should factor out the common bits and make an appropriate interface(s) for each of the special cases.

**Comment by pabloswfly** [comment]
I've merged the content of those three files into one, and I have divided this file into the different scripts and modules that now compose the project.
