### ISSUE TITLE
allow setting seed from command line

### ISSUE THREAD

**Issue by grahamgower** [RacimoLab/genomcmcgan#11]
This would be useful to check for reproducible behaviour before/after making changes. E.g. in #10 I did some profiling, but the results are stochastic because we don't know how long the chain will run. So after making changes that should speed this up, I don't have hard data to confirm.

**Comment by pabloswfly** [comment]
Now both genobuilder.py and genomcmcgan.py accept a seed as an argument (flag -se or --seed). Different runs give the same proposals, discriminator scores, etc...
