### ISSUE TITLE
do simulations on multiple cores

### ISSUE THREAD

**Issue by grahamgower** [RacimoLab/genomcmcgan#3]
Should be fairly easy to wrap calls to `msprime.simulate()` and `stdpopsim_engine.simulate()` with [`concurrent.futures`](https://docs.python.org/3/library/concurrent.futures.html). But I'm not sure if this will have unforseen consequences in terms of interaction with tensorflow.

**Comment by pabloswfly** [comment]
So far there are no conflicts with TF.
