### ISSUE TITLE
From log scale to linear scale

### ISSUE THREAD

**Issue by pabloswfly** [RacimoLab/genomcmcgan#7]
Working in a linear scale should in principle improve the genomcmcgan inference precision and should speed up msprime simulations. However, the HMC object from `tensorflow-probability` suggests new values following a Gaussian distribution with `mean=0` and `stddev=1` at the beginning of the burn-in stage. The MCMCGAN() object classifies these values as outside the parameter bounds (a recombination rate value cannot be i.e. -0.34) and discards the proposal, which results in the chain never getting burned and spoiling the whole sampling.

**Comment by grahamgower** [comment]
Despite using a linear scale, we might need to transform the parameters proposed by the MCMC kernel. But can't invalid parameters be rejected, even during the burnin, by returning a likelihood score of 0?

**Comment by pabloswfly** [comment]
Invalid parameter values (those outside the specific parameter's bounds) are rejected, returning a probability score of 0 (`-np. inf`). But this null likelihood is not informative for the mcmc kernel, and it does not help in proposing a better value in the next iteration.

The initial guess for each parameter, which acts as the initial sampling point for the mcmc chain does not help either. Even if the initial state is 1.25e-8, the first proposal will again be something like -0.34. Maybe I am missing a `tensorflow-probability` function, like a way to bootstrap the results at initialization.

**Comment by grahamgower** [comment]
I'll take a look through the tf-probability docs/code and see if I can find anything, but a transformation should work fine. E.g. if the proposed parameter is `x`, then transform it using something like `x2=1e-8*(1 + x)`. So the MCMC will optimise `x`, and you'll use `x2` for simulation (and then report `x2` as well).

**Comment by grahamgower** [comment]
I looked through the [HMC](https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/mcmc/hmc.py) code and didn't see anything about proposals being suggested by sampling from a Gaussian. It looks like this is using the values in the previous step, and updating them according to momentum values.

**Comment by pabloswfly** [comment]
It was my confusion with the Random Walk kernel. 

It appears the problem is related to the step size parameter for the MCMC kernel, which previously was a fixed value. Now that the algorithm is running much faster I can debug it easier. I will set the parameter to be the standard deviation of each parameter individually.
